# Generated by Django 5.1 on 2024-08-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_descrition', models.TextField()),
                ('recipe_image', models.ImageField(upload_to='recipes/')),
            ],
        ),
    ]
