# Generated by Django 5.1 on 2024-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_recipe_descrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_descrition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(upload_to='recipes/'),
        ),
    ]
