# Generated by Django 5.1 on 2024-08-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_reportcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcard',
            old_name='rank',
            new_name='student_rank',
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
