# Generated by Django 5.1 on 2024-08-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='user_036c4006', max_length=150, unique=True),
        ),
    ]
